const players = [
    {
        "id": parseInt(Math.random()) ,
        "image": "https://i.pinimg.com/564x/28/bf/0c/28bf0c9302a0bd5e1cff15d19ef90e40.jpg",
        "Name": "Lionel Messi",
        "Player_name": "Lionel Messi",
        "teams": ["Fc Barcelona","Psg","InterMiami"],
        "nationalite": "Argentina",
        "skips": 50 ,
        "ballon-Dor": true,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image": "https://i.pinimg.com/564x/48/49/ba/4849ba2ea6517f805785071120cccc08.jpg",
        "Player_name": "Cristiano Ronaldo",
        "Name": "Cristiano Ronaldo",
        "teams": ["Real Madrid","Man United","Juventus","sporting lisbonne","Al naser"],
        "nationalite": "Portugal",
        "skips": 50 ,
        "ballon-Dor": true,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "di maria",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": true,
        "english-winner": true,
        "spanish-winner": true,
        "italian-winner": true,
        "managedByKlop": false ,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()) ,
        "image": "https://i.pinimg.com/564x/82/77/86/82778698e807fce28f39acd73f02e9bd.jpg",
        "Player_name": "Neymar",
        "Name": "Neymar",
        "teams": ["Fc Barcelona","psg","al hilal"],
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/c2/9d/60/c29d602d4cff098695a5833b4372cd36.jpg",
        "Name": "Cryuff",
        "teams": ["Fc Barcelona","Ajax"],
        "nationalite": "Netherland",
        "skips": 50 ,
        "ballon-Dor": true,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/67/45/51/67455117657cf22e7366575edf77a97a.jpg",
        "Name": "Ederson",
        "teams": ["man city","benfica"],
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/57/23/c1/5723c16237c67781ae277902ebb5554f.jpg",
        "Name": "De Bryune",
        "teams": ["man city","chelsea"],
        "nationalite": "belguim",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/26/a0/7a/26a07ae26f22b40de2c7807b54275e4d.jpg",
        "Name": "Walker",
        "teams": ["man city","tottenham"],
        "nationalite": "england",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/ec/98/5e/ec985eeba4983792c3c6644178aab2f3.jpg",
        "Name": "Bernardo Silva",
        "teams": ["man city","benfica"],
        "nationalite": "portugal",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "sterling",
        "teams": ["man city","liverpool","chelsea"],
        "nationalite": "england",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "gundogan",
        "teams": ["man city","bvb","Fc Barcelona"],
        "nationalite": "germany",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "rodri",
        "teams": ["man city","athletico madrid"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "John Stones",
        "teams": ["england","everton"],
        "nationalite": "england",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Fernandinho",
        "teams": "man city",
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Victor Valdes",
        "teams": ["Fc Barcelona","man united"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Dani Alves",
        "teams": ["Fc Barcelona","juventus","psg","seville"],
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Xavi",
        "teams": "Fc Barcelona",
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Foden",
        "teams": "man city",
        "nationalite": "england",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Mahrez",
        "teams": ["man city","Leicester","Al Ahli"],
        "nationalite": "algeria",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Pique",
        "teams": ["Fc Barcelona","man united"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Laporte",
        "teams": ["man city","Al nassr","Bilbao"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Gabriel Jesus",
        "teams": ["man city","arsenal"],
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Busquets",
        "teams": ["Fc Barcelona","InterMiami"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Neuer",
        "teams": ["bayern","Schalke"],
        "nationalite": "germany",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Ruben Dias",
        "teams": ["man city","benfica"],
        "nationalite": "portugal",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Puyol",
        "teams": "Fc Barcelona",
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Iniesta",
        "teams": "Fc Barcelona",
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Otamendi",
        "teams": ["man city","benfica","valencia","porto"],
        "nationalite": "argentina",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "David Silva",
        "teams": ["man city","sosciedad","valencia"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": false ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Name": "Aguero",
        "teams": ["man city","Fc Barcelona","athletico madrid"],
        "nationalite": "argentina",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
]

export default players ;