const players = [
    {
        "id": parseInt(Math.random()) ,
        "image": "https://i.pinimg.com/564x/28/bf/0c/28bf0c9302a0bd5e1cff15d19ef90e40.jpg",
        "Name": "Lionel Messi",
        "Player_name": "Lionel Messi",
        "teams": ["Fc Barcelona","psg","InterMiami"],
        "nationalite": "argentina",
        "skips": 50 ,
        "ballon-Dor": true,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image": "https://i.pinimg.com/564x/48/49/ba/4849ba2ea6517f805785071120cccc08.jpg",
        "Player_name": "Cristiano Ronaldo",
        "Name": "Cristiano Ronaldo",
        "teams": ["Real Madrid","Man United","juventus","sporting lisbonne","El Nasr"],
        "nationalite": "Portugal",
        "skips": 50 ,
        "ballon-Dor": true,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "di maria",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": true,
        "english-winner": true,
        "spanish-winner": true,
        "italian-winner": true,
        "managedByKlop": false ,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()) ,
        "image": "https://i.pinimg.com/564x/82/77/86/82778698e807fce28f39acd73f02e9bd.jpg",
        "Player_name": "Neymar",
        "Name": "Neymar",
        "teams": ["Fc Barcelona","psg","al hilal"],
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/c2/9d/60/c29d602d4cff098695a5833b4372cd36.jpg",
        "Player_name": "Cryuff",
        "teams": ["Fc Barcelona","Ajax"],
        "nationalite": "Netherland",
        "skips": 50 ,
        "ballon-Dor": true,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/67/45/51/67455117657cf22e7366575edf77a97a.jpg",
        "Player_name": "Ederson",
        "teams": ["man city","benfica"],
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/57/23/c1/5723c16237c67781ae277902ebb5554f.jpg",
        "Player_name": "De Bryune",
        "teams": ["man city","chelsea"],
        "nationalite": "belguim",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/26/a0/7a/26a07ae26f22b40de2c7807b54275e4d.jpg",
        "Player_name": "Walker",
        "teams": ["man city","tottenham"],
        "nationalite": "england",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"https://i.pinimg.com/564x/ec/98/5e/ec985eeba4983792c3c6644178aab2f3.jpg",
        "Player_name": "Bernardo Silva",
        "teams": ["man city","benfica"],
        "nationalite": "Portugal",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "sterling",
        "teams": ["man city","liverpool","chelsea"],
        "nationalite": "england",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "gundogan",
        "teams": ["man city","bvb","Fc Barcelona"],
        "nationalite": "germany",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "rodri",
        "teams": ["man city","athletico madrid"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "John Stones",
        "teams": ["england","everton"],
        "nationalite": "england",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Fernandinho",
        "teams": "man city",
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Victor Valdes",
        "teams": ["Fc Barcelona","man united"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Dani Alves",
        "teams": ["Fc Barcelona","juventus","psg","seville"],
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Xavi",
        "teams": "Fc Barcelona",
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Foden",
        "teams": "man city",
        "nationalite": "england",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Mahrez",
        "teams": ["man city","Leicester","Al Ahli"],
        "nationalite": "algeria",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Pique",
        "teams": ["Fc Barcelona","man united"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Laporte",
        "teams": ["man city","Al nassr","Bilbao"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Gabriel Jesus",
        "teams": ["man city","arsenal"],
        "nationalite": "Brazil",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Busquets",
        "teams": ["Fc Barcelona","InterMiami"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Neuer",
        "teams": ["bayern","Schalke"],
        "nationalite": "germany",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Ruben Dias",
        "teams": ["man city","benfica"],
        "nationalite": "Portugal",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Puyol",
        "teams": "Fc Barcelona",
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Iniesta",
        "teams": "Fc Barcelona",
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Otamendi",
        "teams": ["man city","benfica","valencia","porto"],
        "nationalite": "argentina",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "David Silva",
        "teams": ["man city","sosciedad","valencia"],
        "nationalite": "spain",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": false ,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()) ,
        "image":"",
        "Player_name": "Aguero",
        "teams": ["man city","Fc Barcelona","athletico madrid"],
        "nationalite": "argentina",
        "skips": 50 ,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false ,
        "team-mate": "messi",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false ,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Cancelo",
        "teams": ["man city", "juventus"],
        "nationalite": "Portugal",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Abidal",
        "teams": ["Barcelona", "Olympique Lyonnais"],
        "nationalite": "france",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Thomas Muller",
        "teams": ["Bayern Munich"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": true,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "David Alaba",
        "teams": ["Bayern Munich", "Real Madrid"],
        "nationalite": "Austria",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Lahm",
        "teams": ["Bayern Munich"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": true,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Jerome Boateng",
        "teams": ["Bayern Munich"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": true,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Thiago Alcantara",
        "teams": ["Bayern Munich", "liverpool"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Zinchenko",
        "teams": ["man city"],
        "nationalite": "Ukraine",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Yaya Toure",
        "teams": ["man city", "Barcelona"],
        "nationalite": "Ivory Coast",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Sane",
        "teams": ["Bayern Munich", "man city"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Lewandowski",
        "teams": ["Bayern Munich"],
        "nationalite": "Poland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Ake",
        "teams": ["man city", "Chelsea"],
        "nationalite": "Netherland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Grealish",
        "teams": ["man city", "Aston Villa"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Mascherano",
        "teams": ["Barcelona", "liverpool"],
        "nationalite": "argentina",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Mario Gotze",
        "teams": ["bvb", "Bayern Munich"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": true,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Arjen Robben",
        "teams": ["Bayern Munich", "Real Madrid", "Chelsea"],
        "nationalite": "Netherland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Xabi Alonso",
        "teams": ["Real Madrid", "Bayern Munich", "liverpool"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Akanji",
        "teams": ["bvb"],
        "nationalite": "Switzerland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Frank Ribery",
        "teams": ["Bayern Munich", "Fiorentina"],
        "nationalite": "france",
        "skips": 50,
        "ballon-Dor": true,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Benjamin Mendy",
        "teams": ["man city"],
        "nationalite": "france",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "David Villa",
        "teams": ["valencia", "Barcelona", "Atletico Madrid", "New York City FC"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Bravo",
        "teams": ["Real Sociedad", "Barcelona", "man city"],
        "nationalite": "Chile",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Julian Alvarez",
        "teams": ["River Plate"],
        "nationalite": "argentina",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Thierry Henry",
        "teams": ["Monaco", "juventus", "arsenal", "Barcelona", "New York Red Bulls"],
        "nationalite": "france",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Kompany",
        "teams": ["man city", "Anderlecht"],
        "nationalite": "belguim",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": false,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Bastian Schweinsteiger",
        "teams": ["Bayern Munich", "Man United", "Chicago Fire"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Eto'o",
        "teams": ["Real Madrid", "Mallorca", "Fc Barcelona", "Inter Milan", "Chelsea", "Anzhi Makhachkala", "Antalyaspor", "Konyaspor", "Qatar SC"],
        "nationalite": "Cameroon",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Toni Kross",
        "teams": ["Real Madrid", "Bayern Munich"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Douglas Costa",
        "teams": ["Bayern Munich", "juventus"],
        "nationalite": "Brazil",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": true,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Vidal",
        "teams": ["juventus", "Fc Barcelona"],
        "nationalite": "Chile",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Ibrahimovich",
        "teams": ["Man United", "AC Milan"],
        "nationalite": "Sweden",
        "skips": 50,
        "ballon-Dor": true,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": true,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": true,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Cesc Fabregas",
        "teams": ["arsenal", "Fc Barcelona"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Mandzukic",
        "teams": ["Bayern Munich", "juventus"],
        "nationalite": "crotia",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": true,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Benatia",
        "teams": ["Bayern Munich", "juventus"],
        "nationalite": "Morocco",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": true,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Alexis Sanchez",
        "teams": ["Barcelona", "arsenal"],
        "nationalite": "Chile",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": true,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Ferran Torres",
        "teams": ["valencia", "man city"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": true,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Eric Garcia",
        "teams": ["Man City", "FC Barcelona"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Kimmich",
        "teams": ["Bayern Munich"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Kingsley Coman",
        "teams": ["Bayern Munich"],
        "nationalite": "france",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Gvardiol",
        "teams": ["man city"],
        "nationalite": "crotia",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Milito",
        "teams": ["Inter Milan"],
        "nationalite": "argentina",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Zabaleta",
        "teams": ["man city"],
        "nationalite": "argentina",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Jesus Navas",
        "teams": ["seville", "man city"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Kovacic",
        "teams": ["chelsea", "Real Madrid"],
        "nationalite": "crotia",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Cole Palmer",
        "teams": ["man city"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Doku",
        "teams": ["man city","reines"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Angelino",
        "teams": ["man city","leverkusen"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Højbjerg",
        "teams": ["tottenham"],
        "nationalite": "denemark",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Kalvin Phillips",
        "teams": ["man city"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Marc Bartra",
        "teams": ["Fc Barcelona","Betis"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Sergi Roberto",
        "teams": ["Fc Barcelona"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Brahim Diaz",
        "teams": ["Real Madrid"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Pepe Reina",
        "teams": [],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Joe Hart",
        "teams": ["man city"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Samir Nasri",
        "teams": ["arsenal", "man city", "seville", "West Ham United", "Antalyaspor", "Anderlecht"],
        "nationalite": "france",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Luis Diaz",
        "teams": ["Club Brugge", "porto", "liverpool"],
        "nationalite": "Colombia",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Mohammed Salah",
        "teams": ["liverpool", "AS Roma", "Chelsea", "FC Basel"],
        "nationalite": "Egypt",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Roberto Firmino",
        "teams": ["liverpool", "Hoffenheim", "Figueirense"],
        "nationalite": "Brazil",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Trent-Alexandre-Arnold",
        "teams": ["liverpool"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Andrew Robertson",
        "teams": ["liverpool", "Hull City", "Queen's Park"],
        "nationalite": "Scotland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Alisson",
        "teams": ["liverpool", "AS Roma", "Internacional"],
        "nationalite": "Brazil",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Vergil Van Dijk",
        "teams": ["liverpool", "Southampton", "Celtic"],
        "nationalite": "Netherland",
        "skips": 50,
        "ballon-Dor": true,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Jordan Henderson",
        "teams": ["liverpool", "Sunderland", "Coventry City"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Sadio Mane",
        "teams": ["liverpool", "Southampton", "Red Bull Salzburg"],
        "nationalite": "Senegal",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Mats Hummels",
        "teams": ["bvb", "Bayern Munich"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Wijnaldum",
        "teams": ["liverpool", "psg"],
        "nationalite": "Netherland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "James Milner",
        "teams": ["liverpool"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Fabinho",
        "teams": ["liverpool"],
        "nationalite": "Brazil",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Joe Matip",
        "teams": ["liverpool"],
        "nationalite": "Cameroon",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Piszczek",
        "teams": ["bvb"],
        "nationalite": "Poland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Lewandowski",
        "teams": ["Bayern Munich","Fc Barcelona"],
        "nationalite": "Poland",
        "skips": 50,
        "ballon-Dor": true,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Joe Gomez",
        "teams": ["liverpool"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Lovren",
        "teams": ["Zenit Saint Petersburg","liverpool"],
        "nationalite": "crotia",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Marco Reus",
        "teams": ["bvb"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Emre Can",
        "teams": ["bvb", "juventus", "liverpool"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Gundogan",
        "teams": ["man city", "bvb", "FC Barcelona"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": true
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Diego Jota",
        "teams": ["liverpool", "Wolverhampton Wanderers"],
        "nationalite": "Portugal",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Mario Gotze",
        "teams": ["bvb", "Bayern Munich"],
        "nationalite": "germany",
        "skips": 50,
        "ballon-Dor": true,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Mkhitaryan",
        "teams": ["bvb", "Man United", "arsenal", "AS Roma"],
        "nationalite": "Armenia",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Alex Oxlade-Chamberlain",
        "teams": ["arsenal", "liverpool"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Philippe Coutinho",
        "teams": ["liverpool", "FC Barcelona", "Bayern Munich"],
        "nationalite": "Brazil",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Thiago Alcantara",
        "teams": ["FC Barcelona", "Bayern Munich", "liverpool"],
        "nationalite": "spain",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": true,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Naby Keita",
        "teams": ["RB Leipzig", "liverpool"],
        "nationalite": "Guinea",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Aubameyang",
        "teams": ["bvb", "arsenal","chelsea","marseille"],
        "nationalite": "Gabon",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": true,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Ibrahima Konate",
        "teams": ["RB Leipzig", "liverpool"],
        "nationalite": "france",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Sokratis",
        "teams": ["bvb", "arsenal"],
        "nationalite": "Greece",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Luis Diaz",
        "teams": ["porto", "liverpool"],
        "nationalite": "Colombia",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Elliot",
        "teams": ["liverpool"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Darwin Nunez",
        "teams": ["Benfica","liverpool"],
        "nationalite": "Uruguay",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Sturridge",
        "teams": ["liverpool"],
        "nationalite": "england",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Gakpo",
        "teams": ["PSV Eindhoven"],
        "nationalite": "Netherland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Shaquiri",
        "teams": ["liverpool", "Stoke City", "Bayern Munich"],
        "nationalite": "Switzerland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Sakho",
        "teams": ["Crystal Palace", "psg", "West Ham United"],
        "nationalite": "france",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Perisic",
        "teams": ["Inter Milan", "Bayern Munich", "bvb"],
        "nationalite": "crotia",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Minamino",
        "teams": ["liverpool", "RB Salzburg"],
        "nationalite": "Japan",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": true,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Szoboszlai",
        "teams": ["RB Leipzig", "RB Salzburg","liverpool"],
        "nationalite": "Hungary",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Mac Allister",
        "teams": ["Brighton & Hove Albion", "Argentinos Juniors", "liverpool"],
        "nationalite": "argentina",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Benteke",
        "teams": ["Crystal Palace", "liverpool", "Aston Villa"],
        "nationalite": "belguim",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": true,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Ciro Immobile",
        "teams": ["Lazio", "bvb"],
        "nationalite": "italy",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
    {
        "id": parseInt(Math.random()),
        "image": "",
        "Player_name": "Gravenberch",
        "teams": ["Ajax", "psg", "Bayern Munich"],
        "nationality": "Netherland",
        "skips": 50,
        "ballon-Dor": false,
        "worldCup": false,
        "ucl": true,
        "team-mate": "Mbappé",
        "english-Top-Scoorer": false,
        "spanish-Top-Scoorer": false,
        "italian-Top-Scoorer": false,
        "english-winner": false,
        "spanish-winner": false,
        "italian-winner": false,
        "managedByKlop": false,
        "managedByPep": false
    },
]

export default players ;